#!/usr/bin/env python3
import sys


if __name__ == "__main__":
    if(len(sys.argv) < 3):
        print(f"Usage {sys.argv[0]} <input asm> <output asm>")
        sys.exit(1)
    
    sfile = open(sys.argv[1], "r")

    text = False
    cmdline = " ".join(sys.argv)
    lines2 = [
        f"// generated by nopstuffer\n",
        f"// cmdline: {cmdline}\n"
    ]
    for line in sfile:
        lines2.append(line)
        
        # XXX: write a proper parser :)
        line = line.replace("\t", "    ")
        line = line.replace("\n", "")

        # broken for comment tokens in string literals but fuck that
        if "//" in line:
            line = line[:line.index("//")]
        if ";" in line:
            line = line[:line.index(";")]

        # tokenize
        tokens = [t for t in line.split(" ") if t]
        

        if len(tokens) == 0:  # skip empty lines
            continue  
        if tokens[0] == ".text": 
            text = True
        if not text: # skip parsing if not a text section
            continue
        if not tokens[0].startswith(".") and tokens[0][-1] != ":": # Not a directive nor a label, likely an insn
            lines2.append("        nop                    // stuffed\n")  # stuff the nop

    ofile = open(sys.argv[2], "w")
    for l in lines2:
        ofile.write(l)
    ofile.close()
    sfile.close()
    print("Nopstuffer done")
